version: '3.8'

services:
  web:
    build:
      context: .
      target: prod
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
      - nm:/home/node/app/node_modules
    ports:
      - '3000:3000'

volumes:
  nm: